# =========================
# Cấu hình ENCODERS
# =========================

audio:
  # HF model cho Wav2Vec2 (có thể đổi sang model tiếng Việt)
  # Ví dụ: "facebook/wav2vec2-base" hoặc "nguyenvulebinh/wav2vec2-base-vietnamese-250h"
  model_name: "facebook/wav2vec2-base"

video:
  # HF model cho TimeSformer
  model_name: "facebook/timesformer-base-finetuned-k400"
