# =========================
# Cấu hình METADATA PREPROCESS
# =========================

# ---- MODEL NAMES ----
# Text encoder (PhoBERT)
text_model_name: "vinai/phobert-base-v2"

# Toxicity classifier
toxicity_model_name: "funa21/phobert-finetuned-victsd-toxic-v2"

# Constructiveness classifier
construct_model_name: "funa21/phobert-finetuned-victsd-constructiveness-v2"

# Text normalizer (ViNormT5)
norm_model_name: "meoo225/ViNormT5"


# ---- DATE CONFIG ----
# Dùng để tính age_days = reference_date - upload_date
# Format: YYYY-MM-DD
reference_date: "2025-12-05"
assume_year: 2025


# ---- TEXT MAX LENGTHS ----
max_desc_len: 128        # description / caption
max_tags_len: 64         # tags
max_comments_len: 256    # comments (sau khi join bằng [SEP])
