# =========================
# Cấu hình PREPROCESSING
# =========================

# -------- AUDIO ----------
# Sample rate sau khi extract từ video (ffmpeg)
audio_sample_rate: 16000

# -------- VIDEO ----------
# Số frame cố định mỗi video dùng làm input TimeSformer
num_frames: 16

# Kích thước frame sau khi scale (WIDTH, HEIGHT)
frame_size:
  - 224
  - 224
