spark:
  app_name: "TikTokHarmfulContentDetection"
  master: "local[*]"
  
  # MinIO S3A Configuration
  hadoop_conf:
    "fs.s3a.endpoint": "http://localhost:9009"
    "fs.s3a.access.key": "minioadmin"
    "fs.s3a.secret.key": "minioadmin" # Should be overridden by env var in prod
    "fs.s3a.path.style.access": "true"
    "fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "fs.s3a.connection.ssl.enabled": "false"
    
  # Streaming/Batch settings
  batch_duration: 10 

  # Generic Spark Conf
  spark_conf:
    "spark.jars.packages": "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.mongodb.spark:mongo-spark-connector_2.12:10.2.1"
    "spark.sql.extensions": "io.delta.sql.DeltaSparkSessionExtension"
    "spark.sql.catalog.spark_catalog": "org.apache.spark.sql.delta.catalog.DeltaCatalog"
