# =====================================================
# TikTok Crawler Configuration File
# =====================================================

# ====== Playwright Settings ======
timeout_ms: 10000            # Thời gian chờ selectors (ms)
viewport_width: 1280
viewport_height: 720

# ====== Crawl Behavior ======
max_comments_rounds: 20       # Số vòng scroll/comment load
min_sleep_sec: 1.0            # Trễ nhỏ nhất
max_sleep_sec: 2.0            # Trễ lớn nhất
download_video: true          # Có tải video hay không
max_total_comments : 100      # Tổng số lượng comment
max_replies_per_comment : 10  # Số lượng replies tối đa mỗi cmt level 1

# ====== CAPTCHA ==========
captcha_max_wait_sec: 300          # tối đa 5 phút chờ bạn giải
captcha_poll_interval_sec: 5.0     # mỗi 5s check lại một lần


# ====== Hashtag Settings ======
hashtags:                     # Danh sách hashtag để crawl
  - livefest2025
  - xuhuong
  - vannghe2011
  - quoctedanong
  - truytimlongdienhuong
  - bavi
  - mailisa
  - 19thang11
  - quanglinhvlog
  - thuytien
  - salegiuathang
  - huonggiang
  - hangdumuc
  - missuniverse
  - lulut
  - hocsinhcap3 
  - livefest2025    # duplicate
  - xuhuong
  - vannghe2011
  - quoctedanong
  - truytimlongdienhuong
  - bavi
  - mailisa
  - 19thang11
  - quanglinhvlog
  - thuytien
  - salegiuathang
  - huonggiang
  - hangdumuc
  - missuniverse
  - lulut
  - hocsinhcap3
  # - funny
  # - foryou
  # - xuhuong
  # - fyp
  # - sport
  # - dancechallenge
  # - fun
  # - cute
  # - music
  # - besttiktok
max_videos_per_hashtag: 5    # Mỗi hashtag crawl bao nhiêu video

# ====== MinIO Settings ======
minio_config: "config_tiktok.yaml"

# ====== Output ======
export_dir: "exports"
log_file: "logs/tiktok_scraper.log"
tmp_download_dir: "tmp_downloads"
